exp_dir: "experiments/optim/smile_256"

# Data
test_dataset_path: 'data/smile_256/'
test_batch_size: 8
test_workers: 8
stylegan_weights: "artifacts/sg2-ml-smile_256.pt"
resolution: 256

# Hyper-parameter of optimization
optim_step: 1000
optim_l2_lambda: 0.0002
optim_lpips_lambda: 0.5  # only use lpips loss

noise: 0.05
noise_ramp: 0.75
noise_regularize: 1e5
